// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6sNRa2Dj_DCQwKvgI7VpTpRuebaN8_I',
    appId: '1:325369786694:web:af7ce894b127af478d7547',
    messagingSenderId: '325369786694',
    projectId: 'fir-clothingapp-420b1',
    authDomain: 'fir-clothingapp-420b1.firebaseapp.com',
    storageBucket: 'fir-clothingapp-420b1.firebasestorage.app',
    measurementId: 'G-M7JC99S5QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIEKSZHM1Ipz5wIow6p_bqea2sDFh2gXo',
    appId: '1:325369786694:android:fd84f923f1e9baf38d7547',
    messagingSenderId: '325369786694',
    projectId: 'fir-clothingapp-420b1',
    storageBucket: 'fir-clothingapp-420b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWs05yveK03Oypw1rJzhrKdfObIwcFj4k',
    appId: '1:325369786694:ios:5182d09d51f8f1d08d7547',
    messagingSenderId: '325369786694',
    projectId: 'fir-clothingapp-420b1',
    storageBucket: 'fir-clothingapp-420b1.firebasestorage.app',
    iosBundleId: 'com.example.clothing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWs05yveK03Oypw1rJzhrKdfObIwcFj4k',
    appId: '1:325369786694:ios:5182d09d51f8f1d08d7547',
    messagingSenderId: '325369786694',
    projectId: 'fir-clothingapp-420b1',
    storageBucket: 'fir-clothingapp-420b1.firebasestorage.app',
    iosBundleId: 'com.example.clothing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK6sNRa2Dj_DCQwKvgI7VpTpRuebaN8_I',
    appId: '1:325369786694:web:2189abbfc2ac951e8d7547',
    messagingSenderId: '325369786694',
    projectId: 'fir-clothingapp-420b1',
    authDomain: 'fir-clothingapp-420b1.firebaseapp.com',
    storageBucket: 'fir-clothingapp-420b1.firebasestorage.app',
    measurementId: 'G-08EM1EDK3R',
  );
}
